image: 
  repository: nxest/hamster
  tag: "0.0.1"

resourcesPreset: small

tls:
  enabled: false

service: 
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik
  tls: true
  hostname: <%= hostname %>
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer  

serverBlock: |-
  server {
    listen 0.0.0.0:8080;
    location / {
      root /app;
      autoindex on;
      autoindex_exact_size off;
      autoindex_localtime off;
    }
  }