auth:
  adminUser: <%= adminUser %>
  adminPassword: <%= adminPassword %>

ingress:
  enabled: true
  ingressClassName: traefik
  tls: true
  hostname: <%= hostname %>
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer

production: true
# https://www.keycloak.org/server/reverseproxy
proxyHeaders: "xforwarded"
# proxy: "edge"
resourcesPreset: "medium"

networkPolicy:
  enabled: false
postgresql:
  enabled: true
  auth:
    postgresPassword: <%= postgresPassword %>
    username: "keycloak"
    password: <%= postgresPassword %>
    database: "keycloak"

keycloakConfigCli:
  enabled: false
  configuration:
    devops.yaml: |
      realm: devops
      enabled: true
  cleanupAfterFinished:
    enabled: true
