# 需要开启 traefik allowCrossNamespace
#  kubectl -n kube-system edit deployments.apps traefik  
#  --providers.kubernetescrd.allowCrossNamespace=true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    # https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/
    # middlewares 格式为 namespace-middleware@@kubernetescrd，要加 namespace 前缀，如果是 default namespace 也要加 default- 前缀
    traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-errors-sign-in@kubernetescrd
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # https://doc.traefik.io/traefik/routing/routers/#priority
    # traefik.ingress.kubernetes.io/router.priority: "42"
  name: oauth-errors-sign-in
  namespace: oauth2-proxy
spec:
  ingressClassName: traefik
  rules:
  # 这里host我会用pulumi替换掉，只支持一个host
  - host: "*.nxest.com"
    http:
      paths:
      - backend:
          service:
            name: oauth2-proxy
            port:
              name: http
        path: /oauth2
        pathType: Prefix
  tls:
  - hosts:
    - "*.nxest.com"
    secretName: "widles-placeholder-tls"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: errors-sign-in
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: oauth2-proxy
      port: http
      # port: 4180
    query: "/oauth2/sign_in"
    # query: "/oauth2/start?rd=%2F"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Preferred-Username
      - Set-Cookie